name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: FTP Deploy Action
      uses: SamKirkland/FTP-Deploy-Action@1.0.0
      secrets: 
        FTP_USERNAME: ${FTP_USERNAME}
        FTP_PASSWORD: ${FTP_PASSWORD}
        FTP_SERVER: ${FTP_SERVER}
        REMOTE_DIR: ${REMOTE_DIR}
